import logging
from multiprocessing import Pool

import numpy as np
from scipy import signal
from sklearn.decomposition import TruncatedSVD
from models.security import Security

logging.basicConfig(level=logging.INFO,
                    format='%(asctime)s %(levelname)s %(message)s')


def build_fav():
    lookup = {}
    if False:
        tickers = """
        AAAP,AABA,AAL,AAME,AAOI,AAON,AAPC,AAPL,AAWW,AAXJ,AAXN,ABAC,ABAX,ABCB,ABCO,ABEO,ABEOW,ABMD,ABTX,ACAD,
        ACBI,ACFC,ACIU,ACIW,ACLS,ACOR,ACRS,ACSF,ACTX,ACWI,ACWX,ACXM,ADBE,ADES,ADI,ADMA,ADMP,ADMS,ADP,ADRA,
        ADRD,ADRE,ADRO,ADRU,ADSK,AEGN,AEHR,AEIS,AERI,AFH,AGFS,AGFSW,AGII,AGIIL,AGIO,AGNC,AGNCB,AGND,AGYS,
        AGZD,AHGP,AHPA,AHPAU,AHPAW,AHPI,AIA,AIMC,AINV,AIQ,AIRR,AIRT,AKAM,AKAO,AKBA,AKRX,ALBO,ALCO,ALDX,ALGN,
        ALKS,ALLT,ALQA,ALRM,ALSK,ALT,ALTY,ALXN,AMAT,AMBC,AMBCW,AMD,AMED,AMGN,AMKR,AMNB,AMRK,AMRN,AMRS,AMTD,
        AMWD,AMZN,ANAT,ANCB,ANCX,ANDA,ANDAR,ANDAU,ANDAW,ANGI,ANSS,ANY,APDNW,APEI,APOG,APOP,APOPW,APPF,APPN,
        APWC,AQMS,AQXP,ARCB,ARCC,ARII,ARIS,ARKR,ARNA,ARRS,ARTW,ARTX,ARWR,ASBB,ASET,ASMB,ASML,ASPS,ASRV,
        ASRVP,ASUR,ATHN,ATNX,ATRC,ATRI,ATRS,ATSG,ATVI,AUBN,AUDC,AUPH,AVAV,AVEO,AVGO,AVHI,AVNW,AVXS,AXAR,
        AXARU,AXARW,AXAS,AXDX,AXGN,AXSM,AXTI,AZPN,BABY,BANF,BANFP,BANR,BANX,BBC,BBH,BBP,BBRY,BBSI,BCACU,
        BCLI,BCOM,BCOR,BCOV,BCPC,BCTF,BDE,BDSI,BEAT,BECN,BELFA,BFIN,BFIT,BGCP,BGFV,BGNE,BHAC,BHACR,BHACU,
        BHACW,BHBK,BICK,BIDU,BIIB,BIOC,BIOS,BKMU,BL,BLBD,BLDP,BLDR,BLFS,BLIN,BLKB,BLMT,BLRX,BLUE,BLVD,BLVDU,
        BLVDW,BMCH,BMLA,BMLP,BMRC,BMTC,BNCL,BNDX,BNSO,BNTCW,BOBE,BOJA,BOKF,BOLD,BOMN,BOTJ,BOTZ,BPFH,BPFHP,
        BPFHW,BPMC,BPOP,BPOPM,BREW,BRKL,BRKS,BSET,BSFT,BSPM,BSQR,BSRR,BSTG,BTEC,BUFF,BUR,BUSE,BVXV,BVXVW,
        BWFG,BWINA,BZUN,CA,CAC,CACG,CACQ,CAFD,CAKE,CALA,CALD,CAMP,CAMT,CAR,CARA,CARB,CARO,CART,CARV,CARZ,
        CASH,CASS,CATH,CATY,CATYW,CAVM,CBAN,CBAY,CBF,CBIO,CBMX,CBMXW,CBOE,CBRL,CBSH,CCBG,CCLP,CCMP,CCNE,
        CCOI,CCUR,CCXI,CDC,CDL,CDNS,CDTI,CDW,CDZI,CECE,CECO,CELG,CELGZ,CENT,CENTA,CENX,CERC,CERCW,CETV,
        CETXW,CEVA,CEZ,CFA,CFBI,CFBK,CFCO,CFCOU,CFFN,CFNB,CFO,CG,CGBD,CGIX,CGNT,CGNX,CGO,CHCI,CHCO,CHDN,
        CHEK,CHEKW,CHFC,CHI,CHKP,CHRS,CHRW,CHTR,CHUBA,CHUBK,CHW,CHY,CIBR,CID,CIGI,CIL,CINF,CIVB,CIVBP,CIZ,
        CIZN,CLBS,CLDX,CLIR,CLIRW,CLLS,CLMT,CLRBW,CLRBZ,CLUB,CLVS,CLWT,CMCO,CMCSA,CMCT,CME,CNAT,CNBKA,CNCE,
        CNCR,CNFR,CNMD,CNOB,CNTF,CNTY,CNXN,COBZ,COHR,COHU,COKE,COLB,COLM,COMM,COMT,CONE,CONN,COOL,CORI,CORT,
        COST,COUP,COWN,COWNL,CPAH,CPHC,CPIX,CPLP,CPRT,CPRX,CRAI,CRBP,CRDS,CRDT,CREE,CRIS,CRME,CRMT,CRTO,
        CRUS,CRVS,CSA,CSB,CSCO,CSF,CSFL,CSGP,CSII,CSIQ,CSML,CSOD,CSPI,CSQ,CSWI,CSX,CTAS,CTBI,CTIC,CTMX,CTRE,
        CTRL,CTRN,CTRP,CTSH,CUBA,CUI,CUNB,CUR,CVBF,CVCO,CVCY,CVGI,CVGW,CVLT,CVV,CWAY,CWBC,CWST,CXSE,CYAD,
        CYBR,CYCC,CYCCP,CYHHZ,CYOU,CYRN,CYRX,CYRXW,CYTK,CYTR,CYTXW,CZFC,CZWI,DAIO,DAKT,DAX,DBVT,DCOM,DCTH,
        DDBI,DELTW,DENN,DFNL,DFVL,DFVS,DGICB,DGII,DGLD,DGLY,DGRE,DGRS,DGRW,DHIL,DHXM,DISCA,DISCB,DISCK,DISH,
        DLBL,DLBS,DLTH,DLTR,DMTX,DNBF,DNKN,DORM,DOX,DRIOW,DRRX,DRYS,DSGX,DSKEW,DSLV,DSPG,DSWL,DTRM,DTUL,
        DTUS,DTYL,DTYS,DUSA,DVAX,DWAC,DWAQ,DWAS,DWAT,DWCH,DWFI,DWIN,DWLD,DWLV,DXCM,DXGE,DXJS,DXPS,DYNT,DZSI,
        EA,EACQ,EACQU,EACQW,EAGL,EAGLU,EAGLW,EBAY,EBSB,EBTC,ECHO,ECOL,ECPG,EDBI,EEFT,EEI,EEMA,EFAS,EFII,
        EFSC,EGBN,EGLT,EHTH,EIGI,ELEC,ELECW,ELON,EMCB,EMCF,EMCG,EMIF,EMKR,EML,ENFC,ENG,ENOC,ENSG,ENTA,ENTG,
        ENTL,ENZL,ENZY,EPAY,EQBK,EQFN,ERI,ERIC,ERIE,ERII,ESBK,ESEA,ESG,ESGD,ESGE,ESGG,ESGU,ESIO,ESLT,ESPR,
        ETFC,ETRM,ETSY,EUFN,EVBG,EVGBC,EVGN,EVK,EVLMC,EVOK,EVSTC,EWBC,EWZS,EXA,EXAS,EXEL,EXPD,EXPE,EXPO,
        EXTR,EYEGW,EZPW,FAAR,FAB,FAD,FALN,FARO,FB,FBIO,FBIZ,FBMS,FBNC,FBNK,FBSS,FBZ,FCA,FCAN,FCAP,FCBC,FCCY,
        FCEF,FCNCA,FCSC,FCVT,FDEF,FDIV,FDT,FDTS,FDUS,FELE,FEM,FEMB,FEMS,FEP,FEUZ,FEX,FEYE,FFBC,FFBCW,FFIC,
        FFIN,FFIV,FFKT,FFNW,FGEN,FGM,FHB,FHCO,FHK,FIBK,FINX,FISV,FITB,FITS,FIVE,FIVN,FIXD,FIZZ,FJP,FKO,FKU,
        FLAG,FLAT,FLDM,FLEX,FLIR,FLN,FLWS,FLXN,FMAO,FMB,FMBH,FMBI,FMCIR,FMCIU,FMI,FMK,FNGN,FNJN,FNK,FNLC,
        FNSR,FNTE,FNTEU,FNTEW,FNWB,FNX,FNY,FOGO,FOLD,FONE,FONR,FORK,FORM,FORTY,FOXF,FPA,FPXI,FRBA,FRBK,FRED,
        FRGI,FRME,FRPH,FRPT,FSBC,FSBK,FSBW,FSC,FSFG,FSFR,FSLR,FSV,FSZ,FTA,FTAG,FTC,FTCS,FTEO,FTGC,FTHI,FTLB,
        FTNT,FTRI,FTSL,FTW,FTXD,FTXG,FTXH,FTXL,FTXN,FTXO,FTXR,FUEL,FULLL,FULT,FUNC,FUND,FUSB,FV,FVC,FVE,
        FWONA,FWONK,FWP,FWRD,FYC,FYT,FYX,GAIA,GAIN,GAINM,GAINN,GAINO,GALT,GBCI,GBDC,GBLIZ,GBNK,GBT,GCBC,
        GDEN,GEMP,GENC,GENY,GERN,GFED,GFN,GFNCP,GFNSL,GGAL,GIGM,GILT,GLAD,GLBL,GLBS,GLDD,GLMD,GLPG,GLPI,
        GLRE,GLUU,GLYC,GMLP,GNBC,GNCA,GNCMA,GNMK,GNMX,GNRX,GNTX,GOGL,GOGO,GOLD,GOOD,GOODO,GOODP,GOOG,GOOGL,
        GOV,GOVNI,GPAC,GPACU,GPACW,GPIAU,GPIAW,GPIC,GPP,GPRE,GRFS,GRID,GRIF,GSBC,GSHT,GSHTU,GSHTW,GSIT,GSM,
        GSOL,GT,GTLS,GTXI,GTYH,GTYHU,GTYHW,GUID,GULF,GWRS,GYRO,HA,HABT,HAIN,HALL,HAS,HAWK,HBAN,HBANN,HBANO,
        HBCP,HBHC,HBHCL,HBK,HBMD,HBNC,HBP,HCAP,HCAPL,HCOM,HCSG,HDNG,HDP,HDSN,HEES,HFBC,HFBL,HFWA,HIFS,HIIQ,
        HLG,HLIT,HLNE,HMNF,HMST,HMTV,HNH,HOFT,HOLX,HOMB,HONE,HOPE,HOTR,HOVNP,HPJ,HPT,HRZN,HSGX,HSIC,HSKA,
        HSTM,HTBK,HTBX,HTHT,HTLD,HUNT,HUNTU,HUNTW,HURC,HURN,HWBK,HWKN,HYGS,HYLS,HYND,HYZD,IAC,IBCP,IBKC,
        IBKCO,IBKR,IBOC,IBUY,ICBK,ICCC,ICCH,ICFI,ICHR,ICLN,ICLR,ICON,ICUI,IDLB,IDRA,IDSY,IDTI,IDXG,IDXX,IEP,
        IEUS,IFEU,IFGL,IFV,IGF,IGLD,IGOV,III,IIJI,IIVI,IKNX,ILG,ILMN,IMDZ,IMED,IMMR,IMMU,IMMY,IMNP,IMOS,
        IMPV,INAP,INBK,INCR,INCY,INDB,INDY,INFN,INFO,INFR,INGN,INO,INOV,INSE,INSM,INSY,INTC,INTG,INTL,INTU,
        INTX,INVA,INVE,INWK,IONS,IOSP,IOTS,IPAR,IPCC,IPDN,IPGP,IPHS,IPKW,IRBT,IRCP,IRDM,IROQ,IRTC,IRWD,ISBC,
        ISCA,ISHG,ISM,ISRG,ISRL,ISTR,ITEQ,ITI,ITIC,ITRI,ITRN,IVAC,IXUS,IXYS,JACK,JAGX,JASO,JAZZ,JBLU,JBSS,
        JCTCF,JD,JJSF,JKHY,JKI,JOBS,JOUT,JRVR,JSM,JSMD,JSML,JSYN,JSYNR,JSYNU,JSYNW,JUNO,JYNT,KAAC,KAACW,
        KALU,KALV,KBAL,KBLMU,KBWB,KBWD,KBWP,KBWR,KBWY,KCAP,KE,KELYA,KELYB,KEQU,KERX,KEYW,KFFB,KFRC,KINS,
        KITE,KLIC,KLXI,KMDA,KMPH,KNDI,KNSL,KPTI,KRMA,KRNT,KTCC,KTOS,KTWO,KURA,KWEB,LABL,LALT,LAMR,LANDP,
        LARK,LAUR,LAWS,LAYN,LBAI,LBRDA,LBRDK,LBTYB,LBTYK,LCA,LCAHU,LCAHW,LCUT,LDRI,LE,LFUS,LGCYO,LGCYP,LGIH,
        LGND,LHCG,LIFE,LINC,LINK,LION,LITE,LIVE,LJPC,LKFN,LKOR,LKQ,LLNW,LMAT,LMBS,LMFAW,LMNR,LMNX,LMOS,
        LMRKO,LMRKP,LNCE,LNDC,LNGR,LNTH,LOB,LOCO,LOGI,LOGM,LOPE,LORL,LOXO,LPLA,LPNT,LPSN,LRCX,LSBK,LSCC,
        LSXMA,LSXMB,LSXMK,LTBR,LTEA,LVHD,LVNTA,LVNTB,LWAY,LXRX,MACQ,MACQU,MACQW,MAMS,MANT,MAR,MARPS,MASI,
        MATW,MAYS,MB,MBFI,MBOT,MBSD,MBUU,MCBC,MCEF,MCFT,MCHI,MCHP,MCRB,MCRI,MDCO,MDGL,MDIV,MDSO,MDVXW,MDWD,
        MDXG,MEDP,MEIP,MELI,MELR,MEOH,MERC,MESO,MFNC,MGI,MGIC,MGLN,MGPI,MGRC,MGYR,MICTW,MIII,MIIIU,MIIIW,
        MILN,MIME,MINDP,MITL,MKSI,MKTX,MLAB,MLCO,MLHR,MLNK,MLNX,MLVF,MMAC,MMDM,MMDMR,MMDMU,MMDMW,MMLP,MMSI,
        MNDO,MNGA,MNOV,MNTX,MOBL,MOFG,MOGLC,MOMO,MORN,MOSY,MOXC,MPACW,MPB,MPCT,MPWR,MRAM,MRCY,MRNS,MRUS,
        MRVC,MRVL,MSBF,MSCC,MSDIW,MSFG,MSFT,MSON,MSTR,MTBC,MTBCP,MTCH,MTFB,MTFBW,MTGE,MTGEP,MTLS,MTSI,MTSL,
        MU,MVIS,MXIM,MXWL,MYL,MYRG,MYSZ,MZOR,NANO,NATH,NATI,NBIX,NBN,NBRV,NBTB,NCBS,NCIT,NCLH,NCOM,NDAQ,
        NDRM,NDSN,NEOG,NESR,NESRW,NEWS,NEWT,NEWTL,NEWTZ,NFLX,NHLDW,NICE,NKSH,NLST,NNBR,NNDM,NOVT,NRCIA,
        NSEC,NSIT,NSSC,NSTG,NSYS,NTAP,NTCT,NTEC,NTES,NTIC,NTRI,NTRS,NURO,NUROW,NUTR,NUVA,NVAX,NVCR,NVDA,
        NVDQ,NVGN,NVLN,NVMI,NVTR,NVUS,NWBI,NWFL,NWLI,NWPX,NWS,NWSA,NXEOU,NXPI,NXTD,NXTDW,NXTM,NYMT,NYMTO,
        OACQ,OACQR,OACQU,OACQW,OBAS,OBCI,OCC,OCLR,OCUL,ODFL,ODP,OESX,OFED,OFIX,OFLX,OIIM,OKSB,OLBK,OLD,OLED,
        OLLI,OMAB,OMCL,OMER,OMEX,OMNT,ON,ONB,ONEQ,ONSIW,ONSIZ,ONTXW,ONVI,OPB,OPOF,OPTT,ORBC,ORBK,OREX,ORG,
        ORIT,ORMP,ORRF,OSBCP,OSIS,OSN,OSUR,OTEL,OTIC,OTIV,OTTR,OVBC,OVLY,OXBR,OXBRW,OXFD,OXLC,OXLCO,OZRK,
        PAAC,PAACR,PAACU,PAACW,PAAS,PACW,PAGG,PAHC,PANL,PATI,PATK,PAVMW,PAYX,PBBI,PBHC,PBIB,PBNC,PBSK,PBYI,
        PCBK,PCH,PCLN,PCMI,PCO,PCRX,PCSB,PCTI,PCTY,PCYG,PDCO,PDFS,PDLI,PDP,PDVW,PEBK,PEBO,PEGA,PERI,PERY,
        PETS,PETX,PEY,PEZ,PFBC,PFBI,PFBX,PFI,PFIS,PFM,PFMT,PFPT,PGC,PGJ,PGNX,PHO,PI,PICO,PID,PIE,PIH,PIO,
        PIRS,PIZ,PKBK,PKOH,PKW,PLAB,PLBC,PLPC,PLSE,PLUG,PLUS,PLW,PLXP,PLXS,PMBC,PMD,PMPT,PNBK,PNFP,PNK,PNNT,
        PNQI,PNRG,PNTR,PODD,POPE,POWI,PPH,PPHM,PRAA,PRAH,PRFT,PRFZ,PRGS,PRIM,PRN,PRPH,PRPO,PRQR,PRSC,PRTA,
        PRTO,PRXL,PSC,PSCC,PSCD,PSCE,PSCF,PSCH,PSCI,PSCM,PSCT,PSCU,PSDO,PSEC,PSET,PSL,PSTB,PSTI,PTC,PTCT,
        PTF,PTH,PTIE,PTNR,PTX,PUB,PVBC,PXI,PXLW,PY,PYPL,PYZ,PZZA,QABA,QADA,QADB,QAT,QBAK,QCLN,QCRH,QDEL,
        QGEN,QINC,QLC,QLYS,QQEW,QQQ,QQQC,QQQX,QQXT,QRVO,QSII,QTEC,QURE,QVCB,QYLD,RADA,RAIL,RAVN,RBCN,RBPAA,
        RCII,RCKY,RCMT,RCON,RDCM,RDI,RDIB,RDNT,RDVY,RDWR,RECN,REGI,REGN,RELV,RETA,REXX,RFAP,RFDI,RFEM,RFEU,
        RGEN,RGLD,RIBTW,RICK,RILY,RILYL,RLJE,RMBS,RMR,RMTI,RNET,RNST,RNWK,ROBO,ROCK,ROIC,ROLL,ROSEU,RP,RPXC,
        RRGB,RTIX,RTNB,RTRX,RUN,RUSHA,RUSHB,RVEN,RVSB,RXDX,RXIIW,RYAAY,SABR,SAEX,SAFM,SAFT,SAGE,SAIA,SAL,
        SANM,SANW,SASR,SATS,SAUC,SBAC,SBBP,SBBX,SBCF,SBCP,SBFG,SBFGP,SBGI,SBLK,SBLKL,SBNY,SBNYW,SBRA,SBSI,
        SBUX,SCAC,SCACU,SCACW,SCHL,SCHN,SCKT,SCON,SCSC,SCSS,SCZ,SEDG,SEIC,SELF,SENEB,SEV,SFBC,SFLY,SFST,
        SGBK,SGC,SGEN,SGLBW,SGMO,SGMS,SGRP,SGRY,SGYP,SHBI,SHEN,SHIP,SHIPW,SHLD,SHLM,SHOO,SHOR,SHPG,SIEN,
        SIFI,SIFY,SIGI,SIGM,SILC,SINA,SINO,SIRI,SITO,SIVB,SIVBO,SKIS,SKLN,SKOR,SKYW,SKYY,SLAB,SLCT,SLGN,
        SLIM,SLM,SLMBP,SLP,SLQD,SLVO,SMBC,SMBK,SMCP,SMMF,SMMT,SMSI,SMTC,SNBC,SNC,SNDE,SNDX,SNGXW,SNH,SNHY,
        SNLN,SNOAW,SNPS,SNSR,SOCL,SODA,SOHO,SOHOB,SOHOM,SOHU,SONA,SONC,SORL,SOXX,SP,SPAR,SPCB,SPIL,SPKE,
        SPLS,SPNC,SPNS,SPOK,SPPI,SPRT,SPTN,SPWR,SRCE,SRDX,SRET,SREV,SRPT,SRRA,SRTSW,SRUN,SRUNU,SRUNW,SSBI,
        SSC,SSFN,SSNT,SSYS,STB,STBA,STBZ,STDY,STFC,STKL,STLD,STLR,STLRU,STLRW,STML,STMP,STPP,STRA,STRL,STRS,
        STRT,STX,SVA,SVBI,SVRA,SWIN,SWIR,SWKS,SYBT,SYKE,SYMC,SYMX,SYPR,SYRS,TACO,TACOW,TAPR,TAST,TBK,TBNK,
        TBPH,TCBI,TCBIL,TCBIW,TCBK,TCCO,TCFC,TCMD,TCX,TDIV,TEAM,TECD,TECH,TEDU,TERP,TFSL,TGTX,THRM,TIG,TIL,
        TILE,TIPT,TITN,TIVO,TLND,TLT,TNAV,TNXP,TOPS,TORM,TOWN,TRCB,TREE,TRHC,TRIB,TRMB,TRMK,TRNS,TROW,TRS,
        TRST,TRUE,TRUP,TRVG,TSBK,TSC,TSEM,TSLA,TSRI,TTD,TTEK,TTGT,TTMI,TTPH,TTS,TTWO,TURN,TUSA,TUSK,TUTI,
        TUTT,TVIX,TVIZ,TVTY,TWIN,TWNK,TWNKW,TWOU,TXN,TXRH,UAE,UBCP,UBFO,UBND,UBNK,UBNT,UBOH,UBSH,UBSI,UCBA,
        UCBI,UCFC,UCTT,UDBI,UEIC,UFCS,UFPI,UGLD,UHAL,UIHC,ULTI,UMPQ,UNFI,UNTY,UNXL,UPLD,USATP,USAU,USCR,
        USEG,USLB,USLM,USLV,USOI,UTMD,UTSI,UVSP,VALU,VALX,VBFC,VBND,VBTX,VCEL,VCIT,VCLT,VCSH,VCYT,VEAC,
        VEACU,VEACW,VECO,VEON,VGIT,VGLT,VIAV,VIDI,VIGI,VIIX,VIRC,VIRT,VIVO,VKTXW,VLRX,VMBS,VNQI,VOD,VONE,
        VONG,VONV,VREX,VRIG,VRNS,VRSK,VRTS,VRTU,VRTX,VSAR,VSAT,VSDA,VSMV,VSTM,VTHR,VTVT,VTWG,VTWO,VTWV,VUSE,
        VVPR,VVUS,VWOB,VWR,VXUS,VYMI,WAFD,WAFDW,WASH,WAYN,WB,WBA,WBKC,WBMD,WCFB,WDC,WEB,WEBK,WEN,WERN,WFBI,
        WFM,WHF,WHFBL,WHLM,WIFI,WILC,WINA,WING,WINS,WIRE,WIX,WLDN,WLTW,WMAR,WMGI,WMGIZ,WOOD,WOOF,WPPGY,WPRT,
        WRLD,WSBC,WSCI,WSFS,WSFSL,WSTC,WSTG,WSTL,WTBA,WTFC,WTFCW,WVFC,WVVIP,WWD,WYIGU,WYIGW,WYNN,XBKS,XCRA,
        XELAW,XENE,XENT,XGTI,XGTIW,XIV,XLNX,XNCR,XOMA,XRAY,YDIV,YERR,YGYI,YLCO,YLDE,YNDX,YRCW,YTEN,YTRA,YY,
        ZAGG,ZAIS,ZG,ZGNX,ZION,ZIONW,ZIONZ,ZIV,ZIXI,ZN,ZNGA,ZSAN,ZYNE"""
    tickers = """
    AAPL,ADBE,ADI,ADP,ADSK,AKAM,ALXN,AMAT,AMGN,AMZN,ATVI,AVGO,BIDU,BIIB,CA,CELG,CHKP,CHTR,COST,CSCO,
    CSX,CTAS,CTRP,CTSH,DISCA,DISCK,DISH,DLTR,EA,EBAY,EXPE,FB,FISV,GOOG,GOOGL,HAS,HOLX,HSIC,ILMN,INCY,INTC,
    INTU,ISRG,JD,KHC,LBTYK,LRCX,LVNTA,MCHP,MOBL,MSFT,MU,MXIM,MYL,NCLH,NFLX,NTES,NVDA,NXPI,PAYX,PCLN,PYPL,
    REGN,SBAC,SBUX,SHPG,SIRI,STX,SWKS,SYMC,TEAM,TSLA,TXN,VOD,VRSK,VRTX,VSAT,WBA,WDC,XLNX,XRAY,
    ANET,DATA,GLD,LUV,RACE,SNAP,TWLO,TWTR,WMT
    """
    tickers = tickers.replace('\n', '').replace(' ', '').split(',')
    lookup['stocks'] = tickers

    tickers = """
    NEO,ARDR,ARK,BCC,BCH,BLOCK,BTC,BTCD,CVC,DASH,DASH,FUN,GBYTE,ICO,MAID,MYST,NLC2,NXS,PART,PAY,PIVX,PPT,
    QTUM,RDD,SYS,VERI,VIA,WAVES,WINGS,XEM,XVG
    """
    tickers = tickers.replace('\n', '').replace(' ', '').split(',')
    lookup['coins'] = list(map(lambda x: 'coin{}'.format(x), tickers))
    lookup['both'] = lookup['coins'] + lookup['stocks']

    return lookup
tickers_lookup = build_fav()


class Relevancy(object):

    def __init__(self, weighting=(0.4, 0.6), key='n100'):
        self.t = tickers_lookup[key]
        self.weighting = weighting
        self.n_periods = -5

        logging.info('New Relevancy window created for {} weights'.format(weighting))

    @staticmethod
    def transform(inp):
        """ Unused """
        wavelet = signal.ricker
        widths = np.arange(1, 5, 0.05)

        inp = np.nan_to_num(inp)
        X = signal.cwt(inp, wavelet, widths).T

        svd = TruncatedSVD(n_components=1, n_iter=7)
        transformed = svd.fit_transform(X)

        return transformed.reshape((len(X),))

    def value_security(self, ticker):
        crypto = False
        if ticker.startswith('coin'):
            ticker = ticker.replace('coin', '')
            crypto = True

        s = Security.load(ticker, crypto=crypto)

        try:
            with s.span('daily') as so:
                rsi, ma10, _ = so.calc.rsi_values
                r1 = (rsi + ma10) / 2
                # r1 = r1 * so.dataset.volume

            with s.span('weekly') as so:
                rsi, ma10, _ = so.calc.rsi_values
                r2 = (rsi + ma10) / 2
                # r2 = r2 * so.dataset.volume

        except IndexError:
            return None
        finally:
            s.save()

        return (self.weighting[0] * np.mean(r1[self.n_periods:]) +
                self.weighting[1] * np.mean(r2[self.n_periods:])) / 2

    def sortby_relevance(self, only_names=False, limit=200):
        # with Pool(1) as p:
        #     val = p.map(self.value_security, self.t)
        val = map(self.value_security, self.t)

        d = dict(zip(self.t, val))
        d = {k: v for k, v in d.items() if v is not None}

        if only_names:
            return sorted(d, key=d.get)[:limit]

        return [(k, d[k]) for k in sorted(d, key=d.get)][:limit]


if __name__ == '__main__':
    from pprint import pprint
    pprint(Relevancy().sortby_relevance(only_names=False))
